import Nav from "@/components/shared/Nav/Nav";
import Head from "next/head";
import React, { Fragment } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import ShoppingCart from "@/components/shoppingCart/ShoppingCart";

function index() {
    return (
        <Fragment>
            <Head>
                <title>Shopping Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
                    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
                    crossOrigin="anonymous"
                    referrerpolicy="no-referrer"
                />
            </Head>
            <div>
                <Nav />
                <ShoppingCart />
            </div>
        </Fragment>
    );
}

export default index;
