import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/shared/Nav/Nav";
import { useSelector } from "react-redux";
import { selectProduct, setProduct } from "@/store/slices/basketSlice";
import Products from "@/components/products/Products";
import { wrapper } from "@/store/Store";
import "bootstrap/dist/css/bootstrap.min.css";
// import "@fortawesome/fontawesome-svg-core/styles.css"; 

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const product = useSelector(selectProduct);
  return (
    <>
      <Head>
        <title>E-Commerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <div>
        <Nav />
        <Products product={product} />
      </div>
    </>
  );
}

export const getStaticProps = wrapper.getStaticProps((store) => async () => {
  // const response = await fetch(`https://fakestoreapi.com/products`);
  // const data = await response.json();
  // console.log(data);
  // store.dispatch(setProduct(data));
  const response = await fetch('https://advanced-redux-4b354-default-rtdb.firebaseio.com/allProducts.json');
  if( !response.ok ) throw new Error('Failed to fetch data!');
  const data = await response.json();
  for( let key in data ) store.dispatch(setProduct(data[key]));;

});
